name: FnafU
version: '${project.version}'
main: me.udnek.fnafu.FnafU
api-version: '1.20'
depend: [ ProtocolLib ]
commands:
  fnafu:
    description: FnafU
    usage: /fnafu [start/stop/join/leave/debug] [game id] [survivor/animatronic]
    permission: fnafu.admin